const H=[['あ','a'],['い','i'],['う','u'],['え','e'],['お','o'],['か','ka'],['き','ki'],['く','ku'],['け','ke'],['こ','ko'],['さ','sa'],['し','shi'],['す','su'],['せ','se'],['そ','so'],['た','ta'],['ち','chi'],['つ','tsu'],['て','te'],['と','to'],['な','na'],['に','ni'],['ぬ','nu'],['ね','ne'],['の','no'],['は','ha'],['ひ','hi'],['ふ','fu'],['へ','he'],['ほ','ho'],['ま','ma'],['み','mi'],['む','mu'],['め','me'],['も','mo'],['や','ya'],['ゆ','yu'],['よ','yo'],['ら','ra'],['り','ri'],['る','ru'],['れ','re'],['ろ','ro'],['わ','wa'],['を','wo'],['ん','n']];
const K=[['ア','a'],['イ','i'],['ウ','u'],['エ','e'],['オ','o'],['カ','ka'],['キ','ki'],['ク','ku'],['ケ','ke'],['コ','ko'],['サ','sa'],['シ','shi'],['ス','su'],['セ','se'],['ソ','so'],['タ','ta'],['チ','chi'],['ツ','tsu'],['テ','te'],['ト','to'],['ナ','na'],['ニ','ni'],['ヌ','nu'],['ネ','ne'],['ノ','no'],['ハ','ha'],['ヒ','hi'],['フ','fu'],['ヘ','he'],['ホ','ho'],['マ','ma'],['ミ','mi'],['ム','mu'],['メ','me'],['モ','mo'],['ヤ','ya'],['ユ','yu'],['ヨ','yo'],['ラ','ra'],['リ','ri'],['ル','ru'],['レ','re'],['ロ','ro'],['ワ','wa'],['ヲ','wo'],['ン','n']];
const CONF=[['あ','お'],['き','さ'],['ぬ','め'],['れ','わ'],['シ','ツ'],['ソ','ン']];
const KEY='gojuon-v12';
let S=JSON.parse(localStorage.getItem(KEY)||'null')||{mode:'hira',learned:[],wrong:{},correct:{},streak:0,lastDay:'',daily:[],guide:1,voice:'',rate:.82};
if(S.voice===undefined)S.voice=''; if(S.rate===undefined)S.rate=.82;
const today=()=>new Date().toLocaleDateString('sv-SE');
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function touchDay(){let t=today();if(S.lastDay!==t){let d=new Date();d.setDate(d.getDate()-1);let y=d.toLocaleDateString('sv-SE');S.streak=S.lastDay===y?S.streak+1:1;S.lastDay=t;S.daily=[];save()}}touchDay();
const data=()=>S.mode==='hira'?H:K;
let JPVOICES=[];
function refreshVoices(){JPVOICES=speechSynthesis.getVoices().filter(v=>/^ja[-_]/i.test(v.lang));if(!S.voice&&JPVOICES.length){let best=JPVOICES.find(v=>/Kyoko|Otoya|Nanami|Japanese/i.test(v.name))||JPVOICES[0];S.voice=best.name;save()}let sel=document.querySelector('#voiceSelect');if(sel)fillVoiceSelect(sel)}
function fillVoiceSelect(sel){let current=S.voice;sel.innerHTML=JPVOICES.length?JPVOICES.map(v=>`<option value="${esc(v.name)}" ${v.name===current?'selected':''}>${v.name} (${v.lang})</option>`).join(''):`<option>裝置預設日文語音</option>`}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
refreshVoices();speechSynthesis.onvoiceschanged=refreshVoices;
function speak(k,rate=S.rate){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(k);u.lang='ja-JP';u.rate=rate;u.pitch=1;u.volume=1;let v=JPVOICES.find(x=>x.name===S.voice);if(v)u.voice=v;speechSynthesis.speak(u)}
function root(html){document.querySelector('#app').innerHTML=`<div class='wrap'>${html}<div class='footer'>五十音學習 App V1.2 · 學習紀錄保存在這台裝置</div></div>`}
function header(sub='智慧五十音教練'){return `<div class='top'><div class='brand'><div class='logo'>あ</div><div><div class='title'>五十音學習</div><div class='ver'>V1.2 · ${sub}</div></div></div><span class='pill'>🔥 ${S.streak} 天</span></div>`}
function back(label='首頁'){return `<button class='btn small' onclick='home()'>← ${label}</button>`}
function home(){let total=H.length+K.length,pct=Math.round(S.learned.length/total*100);root(`${header()}<div class='card hero'><div class='heroLine'><div><div class='heroSub'>你的學習進度</div><div class='heroBig'>${pct}%</div></div><div class='heroSub'>已學會 ${S.learned.length} / ${total}</div></div><div class='progress' style='margin-top:12px'><i style='width:${pct}%'></i></div></div><div class='card grid'><button class='btn primary' onclick='learn()'>🔊 點字學發音</button><button class='btn' onclick='writeMode()'>✍️ 手寫練習</button><button class='btn' onclick='quiz("listen")'>🎧 聽音選字</button><button class='btn' onclick='quiz("read")'>🧠 看字選音</button><button class='btn' onclick='review()'>🔁 智慧複習</button><button class='btn' onclick='confuse()'>👀 易混淆字</button></div><div class='card'><div class='sectionTitle'>學習文字</div><div class='sectionSub'>先熟悉平假名，再進看片假名。</div><div class='tabs'><button class='btn ${S.mode==='hira'?'primary':''}' onclick='setMode("hira")'>平假名</button><button class='btn ${S.mode==='kata'?'primary':''}' onclick='setMode("kata")'>片假名</button></div></div><div class='card'><div class='sectionTitle'>🔈 日文發音</div><div class='sectionSub'>自動優先使用裝置內的日文 ja-JP 語音。iPhone 可選擇不同日文聲音。</div><div class='voiceBox'><select id='voiceSelect' class='voiceSelect' onchange='changeVoice(this.value)'></select><button class='btn small soft' onclick='speak("あ")'>試聽 あ</button></div><div class='row' style='margin-top:10px'><button class='btn small ${S.rate===.82?'primary':''}' onclick='setRate(.82)'>自然速度</button><button class='btn small ${S.rate===.62?'primary':''}' onclick='setRate(.62)'>初學慢速</button></div><div class='miniNote' style='margin-top:9px'>語音品質由手機系統提供；若裝置有多個日文語音，可在這裡切換比較。</div></div><div class='card'><div class='sectionTitle'>今天</div><div class='muted'>已完成 <b>${S.daily.length}</b> 次練習。答錯較多的音會自動增加出題次數。</div></div>`);setTimeout(refreshVoices,0)}
function changeVoice(v){S.voice=v;save();speak('あいうえお')}
function setRate(r){S.rate=r;save();home();setTimeout(()=>speak('あいうえお'),80)}
function setMode(m){S.mode=m;save();home()}
function rowData(){let D=data();return [
 ['母音',D.slice(0,5)],['K',D.slice(5,10)],['S',D.slice(10,15)],['T',D.slice(15,20)],['N',D.slice(20,25)],['H',D.slice(25,30)],['M',D.slice(30,35)],['Y',[D[35],D[36],D[37]]],['R',D.slice(38,43)],['W',[D[43],D[44],D[45]]]
]}
function learn(){root(`<div class='row space'>${back()}<span class='pill'>${S.mode==='hira'?'平假名':'片假名'}</span></div><div class='card'><div class='sectionTitle'>點一個假名，就直接發音</div><div class='sectionSub'>綠點代表已學會；點同一個字可重複聽不限次數。</div><div class='kanaRows'>${rowData().map(([label,items])=>`<div class='kanaRow'><div class='rowLabel'>${label}</div>${items.map(([k,r])=>`<button class='kanaBtn ${S.learned.includes(k)?'learned':''}' id='kb-${k}' onclick='showKana("${k}","${r}")'>${k}${S.learned.includes(k)?'<i class="dot"></i>':''}</button>`).join('')}${items.length<5?'<span></span>'.repeat(5-items.length):''}</div>`).join('')}</div></div><div id='detail'></div>`)}
function showKana(k,r){speak(k);document.querySelectorAll('.kanaBtn').forEach(b=>b.classList.remove('active'));let b=document.getElementById(`kb-${k}`);if(b)b.classList.add('active');document.querySelector('#detail').innerHTML=`<div class='card center'><div class='studyHead'><span class='pill'>點大字也會發音</span><button class='btn small soft' onclick='speak("${k}",.56)'>🐢 慢速</button></div><button style='border:0;background:transparent;width:100%;color:inherit' onclick='speak("${k}")'><div class='studyKana'>${k}</div><div class='roman'>${r}</div><div class='tapHint'>🔊 再點一次重聽</div></button><div class='row' style='justify-content:center;margin-top:14px'><button class='btn primary' onclick='markLearned("${k}")'>✓ 我學會了</button><button class='btn' onclick='writeSpecific("${k}","${r}")'>✍️ 練習寫</button></div></div>`}
function markLearned(k){if(!S.learned.includes(k))S.learned.push(k);save();let b=document.getElementById(`kb-${k}`);if(b){b.classList.add('learned');if(!b.querySelector('.dot'))b.insertAdjacentHTML('beforeend','<i class="dot"></i>')}}
function rand(arr){return arr[Math.floor(Math.random()*arr.length)]}
function weightedPool(){let D=data(),pool=[];D.forEach(x=>{let w=1+(S.wrong[x[0]]||0)*2;for(let i=0;i<w;i++)pool.push(x)});return pool}
function quiz(type){let q=rand(weightedPool()),opts=[q];while(opts.length<4){let x=rand(data());if(!opts.some(o=>o[0]===x[0]))opts.push(x)}opts.sort(()=>Math.random()-.5);root(`<div class='row space'>${back()}<span class='pill'>${type==='listen'?'聽音選字':'看字選音'}</span></div><div class='card center'>${type==='listen'?`<button class='btn soft' style='width:100%;min-height:130px' onclick='speak("${q[0]}")'><div style='font-size:42px'>🔊</div><div>再聽一次</div></button>`:`<button style='border:0;background:transparent;color:inherit' onclick='speak("${q[0]}")'><div class='studyKana'>${q[0]}</div><div class='tapHint'>點字可聽發音</div></button>`}<div id='choices' style='margin-top:14px'>${opts.map(o=>`<button class='choice' onclick='answer(this,"${q[0]}","${type==='listen'?o[0]:o[1]}","${type}","${q[1]}")'>${type==='listen'?o[0]:o[1]}</button>`).join('')}</div><div id='fb' class='muted' style='margin-top:10px'></div></div>`);if(type==='listen')speak(q[0])}
function answer(btn,k,val,type,roman){let ok=type==='listen'?val===k:val===roman;[...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true);btn.classList.add(ok?'ok':'bad');if(ok){S.correct[k]=(S.correct[k]||0)+1;if((S.wrong[k]||0)>0)S.wrong[k]--;document.querySelector('#fb').textContent='答對了！';speak(k)}else{S.wrong[k]=(S.wrong[k]||0)+1;document.querySelector('#fb').textContent=`答錯了，正確答案：${k} / ${roman}`;speak(k)}S.daily.push({k,ok,t:Date.now()});save();setTimeout(()=>quiz(type),1150)}
function review(){let D=data().slice().sort((a,b)=>(S.wrong[b[0]]||0)-(S.wrong[a[0]]||0));let top=D.filter(x=>(S.wrong[x[0]]||0)>0).slice(0,10);if(!top.length)top=D.filter(x=>!S.learned.includes(x[0])).slice(0,10);root(`<div class='row'>${back()}</div><div class='card'><div class='sectionTitle'>智慧複習</div><div class='sectionSub'>點字立即聽音；系統優先放入常答錯或尚未學會的假名。</div><div class='grid'>${top.map(([k,r])=>`<button class='btn' style='font-size:28px' onclick='speak("${k}")'>${k}<small style='display:block;font-size:12px;color:var(--muted);margin-top:3px'>${r}</small></button>`).join('')}</div><div class='center' style='margin-top:14px'><button class='btn primary' onclick='quiz("listen")'>開始聽力複習</button></div></div>`)}
function confuse(){root(`<div class='row'>${back()}</div><div class='card'><div class='sectionTitle'>容易混淆</div><div class='sectionSub'>每個按鈕會唸出左邊的字；注意兩個字的筆畫差異。</div><div class='confuse'>${CONF.map(p=>`<button class='btn' onclick='speak("${p[0]}")'>${p[0]} ／ ${p[1]}</button>`).join('')}</div></div>`)}
function writeMode(){let [k,r]=rand(data());writeSpecific(k,r)}
function writeSpecific(k,r){root(`<div class='row space'>${back()}<span class='pill'>手寫 ${k} / ${r}</span></div><div class='card center'><button style='border:0;background:transparent;color:inherit' onclick='speak("${k}")'><div class='studyKana' style='font-size:58px;margin:0'>${k}</div><div class='tapHint'>點字聽發音</div></button><div class='row' style='justify-content:center;margin-top:8px'><button class='btn small soft' onclick='speak("${k}")'>🔊 發音</button><button class='btn small' onclick='toggleGuide()'>👁 描字 ${S.guide?'開':'關'}</button><button class='btn small' onclick='writeMode()'>下一個</button></div><div class='canvasWrap'><div class='guide' id='guide' style='display:${S.guide?'grid':'none'}'>${k}</div><canvas id='pad'></canvas></div><div class='row' style='justify-content:center'><button class='btn' onclick='clearPad()'>清除</button><button class='btn primary' onclick='finishWrite("${k}")'>完成這個字</button></div></div>`);setTimeout(initPad,0);speak(k)}
function finishWrite(k){if(!S.learned.includes(k))S.learned.push(k);S.daily.push({k,ok:true,t:Date.now(),type:'write'});save();writeMode()}
function toggleGuide(){S.guide=S.guide?0:1;save();let g=document.querySelector('#guide');if(g)g.style.display=S.guide?'grid':'none'}
let ctx,canvas,drawing=false;
function initPad(){canvas=document.querySelector('#pad');let r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=8;ctx.strokeStyle='#24211f';let pos=e=>{let rr=canvas.getBoundingClientRect();return[e.clientX-rr.left,e.clientY-rr.top]};let start=e=>{drawing=true;let [x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y);e.preventDefault()};let move=e=>{if(!drawing)return;let [x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke();e.preventDefault()};let end=e=>{if(!drawing)return;drawing=false;e.preventDefault()};canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('pointerleave',end)}
function clearPad(){if(ctx&&canvas){let r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height)}}
home();
