const H=[['あ','a'],['い','i'],['う','u'],['え','e'],['お','o'],['か','ka'],['き','ki'],['く','ku'],['け','ke'],['こ','ko'],['さ','sa'],['し','shi'],['す','su'],['せ','se'],['そ','so'],['た','ta'],['ち','chi'],['つ','tsu'],['て','te'],['と','to'],['な','na'],['に','ni'],['ぬ','nu'],['ね','ne'],['の','no'],['は','ha'],['ひ','hi'],['ふ','fu'],['へ','he'],['ほ','ho'],['ま','ma'],['み','mi'],['む','mu'],['め','me'],['も','mo'],['や','ya'],['ゆ','yu'],['よ','yo'],['ら','ra'],['り','ri'],['る','ru'],['れ','re'],['ろ','ro'],['わ','wa'],['を','wo'],['ん','n']];
const K=[['ア','a'],['イ','i'],['ウ','u'],['エ','e'],['オ','o'],['カ','ka'],['キ','ki'],['ク','ku'],['ケ','ke'],['コ','ko'],['サ','sa'],['シ','shi'],['ス','su'],['セ','se'],['ソ','so'],['タ','ta'],['チ','chi'],['ツ','tsu'],['テ','te'],['ト','to'],['ナ','na'],['ニ','ni'],['ヌ','nu'],['ネ','ne'],['ノ','no'],['ハ','ha'],['ヒ','hi'],['フ','fu'],['ヘ','he'],['ホ','ho'],['マ','ma'],['ミ','mi'],['ム','mu'],['メ','me'],['モ','mo'],['ヤ','ya'],['ユ','yu'],['ヨ','yo'],['ラ','ra'],['リ','ri'],['ル','ru'],['レ','re'],['ロ','ro'],['ワ','wa'],['ヲ','wo'],['ン','n']];
const CONF=[['あ','お'],['き','さ'],['ぬ','め'],['れ','わ'],['シ','ツ'],['ソ','ン']];
const KEY='gojuon-v12';
let S=JSON.parse(localStorage.getItem(KEY)||'null')||{mode:'hira',learned:[],wrong:{},correct:{},streak:0,lastDay:'',daily:[],guide:1};
const today=()=>new Date().toISOString().slice(0,10);function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function touchDay(){let t=today();if(S.lastDay!==t){let d=new Date();d.setDate(d.getDate()-1);let y=d.toISOString().slice(0,10);S.streak=S.lastDay===y?S.streak+1:1;S.lastDay=t;S.daily=[];save()}}
touchDay();
const data=()=>S.mode==='hira'?H:K; const all=()=>[...H,...K];
function speak(k,rate=.85){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(k);u.lang='ja-JP';u.rate=rate;speechSynthesis.speak(u)}
function root(html){document.querySelector('#app').innerHTML=`<div class='wrap'>${html}<div class='footer'>五十音學習 App V1.2 · 資料保存在此裝置瀏覽器</div></div>`}
function home(){let total=H.length+K.length, pct=Math.round(S.learned.length/total*100);root(`<div class='top'><div><div class='title'>🇯🇵 五十音學習</div><div class='ver'>V1.2 智慧複習版</div></div><span class='pill'>🔥 ${S.streak} 天</span></div><div class='card'><div class='stat'><span>總進度</span><b>${S.learned.length}/${total}</b></div><div class='progress'><i style='width:${pct}%'></i></div></div><div class='card grid'><button class='btn primary' onclick='learn()'>🔊 學五十音</button><button class='btn' onclick='writeMode()'>✍️ 手寫練習</button><button class='btn' onclick='quiz("listen")'>🎧 聽音選字</button><button class='btn' onclick='quiz("read")'>🧠 看字選音</button><button class='btn' onclick='review()'>🔁 智慧複習</button><button class='btn' onclick='confuse()'>👀 易混淆字</button></div><div class='card'><div class='sectionTitle'>學習模式</div><div class='tabs'><button class='btn ${S.mode==='hira'?'primary':''}' onclick='setMode("hira")'>平假名</button><button class='btn ${S.mode==='kata'?'primary':''}' onclick='setMode("kata")'>片假名</button></div></div><div class='card'><div class='sectionTitle'>今天</div><div class='muted'>已完成 ${S.daily.length} 次練習。系統會優先安排你常答錯的假名。</div></div>`)}
function setMode(m){S.mode=m;save();home()}
function learn(){let D=data();root(`<div class='row'><button class='btn small' onclick='home()'>← 首頁</button><span class='pill'>${S.mode==='hira'?'平假名':'片假名'}</span></div><div class='card'><div class='sectionTitle'>每次 5 個音</div><div class='five'>${D.map(([k,r],i)=>`<button class='kanaBtn ${S.learned.includes(k)?'learned':''}' onclick='showKana(${i})'>${k}</button>`).join('')}</div></div><div id='detail'></div>`)}
function showKana(i){let [k,r]=data()[i];document.querySelector('#detail').innerHTML=`<div class='card center'><div class='kana'>${k}</div><div class='roman'>${r}</div><div class='row' style='justify-content:center;margin-top:12px'><button class='btn primary' onclick='speak("${k}")'>🔊 發音</button><button class='btn' onclick='speak("${k}",0.55)'>🐢 慢速</button><button class='btn' onclick='markLearned("${k}")'>✓ 我學會了</button></div></div>`}
function markLearned(k){if(!S.learned.includes(k))S.learned.push(k);save();learn()}
function rand(arr){return arr[Math.floor(Math.random()*arr.length)]}
function weightedPool(){let D=data(), pool=[];D.forEach(x=>{let w=1+(S.wrong[x[0]]||0)*2;for(let i=0;i<w;i++)pool.push(x)});return pool}
function quiz(type){let q=rand(weightedPool());let opts=[q];while(opts.length<4){let x=rand(data());if(!opts.some(o=>o[0]===x[0]))opts.push(x)}opts.sort(()=>Math.random()-.5);root(`<div class='row'><button class='btn small' onclick='home()'>← 首頁</button><span class='pill'>${type==='listen'?'聽音選字':'看字選音'}</span></div><div class='card center'>${type==='listen'?`<div class='kana'>🎧</div><button class='btn primary' onclick='speak("${q[0]}")'>播放聲音</button>`:`<div class='kana'>${q[0]}</div>`}<div id='choices' style='margin-top:14px'>${opts.map(o=>`<button class='choice' onclick='answer(this,"${q[0]}","${type==='listen'?o[0]:o[1]}","${type}","${q[1]}")'>${type==='listen'?o[0]:o[1]}</button>`).join('')}</div><div id='fb' class='muted' style='margin-top:10px'></div></div>`);if(type==='listen')setTimeout(()=>speak(q[0]),250)}
function answer(btn,k,val,type,roman){let ok=type==='listen'?val===k:val===roman;[...document.querySelectorAll('.choice')].forEach(b=>b.disabled=true);btn.classList.add(ok?'ok':'bad');if(ok){S.correct[k]=(S.correct[k]||0)+1;if((S.wrong[k]||0)>0)S.wrong[k]--;document.querySelector('#fb').textContent='答對了！';speak(k)}else{S.wrong[k]=(S.wrong[k]||0)+1;document.querySelector('#fb').textContent=`答錯了，正確答案：${k} / ${roman}`;}S.daily.push({k,ok,t:Date.now()});save();setTimeout(()=>quiz(type),900)}
function review(){let D=data().slice().sort((a,b)=>(S.wrong[b[0]]||0)-(S.wrong[a[0]]||0));let top=D.filter(x=>(S.wrong[x[0]]||0)>0).slice(0,10);if(!top.length)top=D.filter(x=>!S.learned.includes(x[0])).slice(0,10);root(`<div class='row'><button class='btn small' onclick='home()'>← 首頁</button></div><div class='card'><div class='sectionTitle'>智慧複習</div><div class='muted'>優先複習錯誤率較高或還沒學會的假名。</div><div class='five' style='margin-top:12px'>${top.map(([k,r])=>`<button class='kanaBtn' onclick='speak("${k}")'>${k}</button>`).join('')}</div><div class='center' style='margin-top:14px'><button class='btn primary' onclick='quiz("listen")'>開始聽力複習</button></div></div>`)}
function confuse(){root(`<div class='row'><button class='btn small' onclick='home()'>← 首頁</button></div><div class='card'><div class='sectionTitle'>容易混淆</div><div class='confuse'>${CONF.map(p=>`<button class='btn' onclick='speak("${p[0]}")'>${p[0]} ／ ${p[1]}</button>`).join('')}</div><div class='muted' style='margin-top:12px'>點一下先聽左邊發音，再自己比較字形。</div></div>`)}
function writeMode(){let D=data();let [k,r]=rand(D);root(`<div class='row'><button class='btn small' onclick='home()'>← 首頁</button><span class='pill'>手寫：${k} / ${r}</span></div><div class='card center'><div class='row' style='justify-content:center'><button class='btn small' onclick='speak("${k}")'>🔊 發音</button><button class='btn small' onclick='toggleGuide()'>👁 描字 ${S.guide?'開':'關'}</button><button class='btn small' onclick='writeMode()'>下一個</button></div><div class='canvasWrap'><div class='guide' id='guide' style='display:${S.guide?'grid':'none'}'>${k}</div><canvas id='pad'></canvas></div><div class='row' style='justify-content:center'><button class='btn' onclick='clearPad()'>清除</button><button class='btn primary' onclick='markLearned("${k}");writeMode()'>完成這個字</button></div></div>`);setTimeout(initPad,0)}
function toggleGuide(){S.guide=S.guide?0:1;save();let g=document.querySelector('#guide');if(g)g.style.display=S.guide?'grid':'none'}
let ctx,canvas,drawing=false;function initPad(){canvas=document.querySelector('#pad');let r=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=8;ctx.strokeStyle='#222';let pos=e=>{let rr=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return[p.clientX-rr.left,p.clientY-rr.top]};let start=e=>{drawing=true;let [x,y]=pos(e);ctx.beginPath();ctx.moveTo(x,y);e.preventDefault()};let move=e=>{if(!drawing)return;let [x,y]=pos(e);ctx.lineTo(x,y);ctx.stroke();e.preventDefault()};let end=e=>{drawing=false;e.preventDefault()};canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end)}
function clearPad(){if(ctx&&canvas){let r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height)}}
home();
